#!/bin/sh

if git diff --cached | grep -q 'define WIFI_PASSWD [^ ]*'
then
  echo "ERROR: Commit contains 'define WIFI_PASSWD' with a non-empty value, remove it before committing."
  exit 1
fi

if git diff --cached | grep -q 'define WIFI_SSID [^ ]*'
then
  echo "ERROR: Commit contains 'define WIFI_SSID' with a non-empty value, remove it before committing."
  exit 1
fi

if git diff --cached | grep -q 'define WEATHER_API_KEY [^ ]*'
then
  echo "ERROR: Commit contains 'define WEATHER_API_KEY' with a non-empty value, remove it before committing."
  exit 1
fi
